####################################
#     Autoruns
####################################
# --- Aplikasi yang hanya perlu jalan 1x (Startup) ---
exec --no-startup-id xset r rate 220 35 &
#exec --no-startup-id udiskie -t &

exec --no-startup-id ~/Projects/python-gesture/venv/bin/python ~/Projects/python-gesture/python-gesture.py

# --- Script yang dijalankan ulang setiap Reload ---
# Ini akan memicu semua script visual & autotiling di autostart.sh
exec_always --no-startup-id ~/.config/i3/scripts/autostart.sh
