;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;     ______      __
;    / ________  / ____  __________
;   / /   / __ \/ / __ \/ ___/ ___/
;  / /___/ /_/ / / /_/ / /  (__  )
;  \____/\____/_/\____/_/  /____/
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[colors]

;324
;background = ${xrdb:color3:#1a1b26}
;background-alt = ${xrdb:color2:#2f363d}
;background-alt0 = ${xrdb:color4:#1A232E}

;081
background = ${xrdb:background:#1a1b26}
background-alt = ${xrdb:color4:#2f363d}
background-alt0 = ${xrdb:color2:#1A232E}

transparent = #00000000
foreground = ${xrdb:foreground:#adb1b9}


primary = ${xrdb:color0:#2E3440}
secondary = ${xrdb:color7:#8FBCBB}
alert = #da4453
disabled = #3A3A3A
border = ${xrdb:color2:#434C5E}
green = ${xrdb:color14:#A3BE8C}

color0 = ${xrdb:color0:#2E3440}
color1 = ${xrdb:color1:#3B4252}
color2 = ${xrdb:color2:#434C5E}
color3 = ${xrdb:color3:#4C566A}
color4 = ${xrdb:color4:#D8DEE9}
color5 = ${xrdb:color5:#ECEFF4}
color6 = ${xrdb:color6:#5E81AC}
color7 = ${xrdb:color7:#8FBCBB}
color8 = ${xrdb:color8:#88C0D0}
color9 = ${xrdb:color9:#81A1C1}
color10 = ${xrdb:color10:#5E81AC}
color11 = ${xrdb:color11:#BF616A}
color12 = ${xrdb:color12:#D08770}
color13 = ${xrdb:color13:#EBCB8B}
color14 = ${xrdb:color14:#A3BE8C}
color15 = ${xrdb:color15:#B48EAD}
dark-light = #272A2B 
active-light = #313435
dark = #000000

