;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[global/wm]
include-file = colors.ini
include-file = modules.ini
include-file = decor.ini
include-file = script-module.ini

margin-top = 0
margin-bottom = 0

[var]
pad = 1

[bar/main]
monitor = ${env:MONITOR:}
; Use the specified monitor as a fallback if the main one is not found.
monitor-fallback = eDP-1
dpi = 96

;bar pos
bottom = false

;bar size
width = 99.5%
;width = 1728
height = 2.5%

;offset
; ## (100−98)/2  ##
offset-x = 0.3%
offset-y = 0.4%

;border
border-size = 3
;border-top-size = 3 px
;border-bottom-size = 3 px
;border-left-size = 3 px
;border-right-size = 3 px

border-color = ${colors.background}

;radius
radius = 1
;radius-top = 15
;radius-bottom = 15

;bar color
;background = ${colors.transparent}
background = ${colors.background}
foreground = ${colors.foreground}

;under/top line
line-size = 3

;padding = 
;padding-left = 0px
;padding-right = 0px

; Essential for floating
;layer = top
;layer = overlay

#floating
override-redirect = true
fixed-center = true
;position = top

;wm-restack = generic
;wm-restack = bspwm
wm-restack = i3

enable-struts = true
;==========================================================
; font
;==========================================================

;font
font-0 = "JetBrainsMono Nerd Font Propo:size=12;3"
font-1 = "MesloLGS NF:size=14;3"
font-2 = "JetBrainsMono Nerd Font Propo:style:Bold:size=14;3"
;icon
font-3 = "waffle:size=10;3"
font-4 = "Iosevka Nerd Font:style=Medium:size=14;4"
font-5 = "JetBrainsMono Nerd Font Propo:size=19,5;5"
font-6 = "feather:style=Medium:size=14;3"
font-7 = "Noto Sans:size=10;2"
font-8 = "Noto Sans CJK JP:size=10;2"
font-9 = "Symbols Nerd Font:size=12;3"
font-10 = "Noto Sans Thai:size=10;2"

;==========================================================
; POSITION MODULE
;==========================================================

modules-left = xworkspaces 
modules-center = 
modules-right = a1 mpd sep date sep prayer sep wlan bluetooth light gammastep caffein sep eth memory cpu battery pulseaudio sep tray sysmenu

;module-margin = 1
;separator = ""
;separator-foreground = ${colors.disabled}
;==========================================================
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
;tray-position = right
dim-value = 1.0



[settings]
screenchange-reload = true
pseudo-transparency = true

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

log-level = warning; Options: error, warning, info, trace
; vim:ft=dosini
