;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;      __  ___          __      __
;     /  |/  ____  ____/ __  __/ ___  _____
;    / /|_/ / __ \/ __  / / / / / _ \/ ___/
;   / /  / / /_/ / /_/ / /_/ / /  __(__  )
;  /_/  /_/\____/\__,_/\__,_/_/\___/____/
;
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;==========================================================
; MODULE
;==========================================================
;%{F#d29922} TEXT%{F-}

[module/mpd]
type = internal/mpd

; Host where mpd is running (either ip or domain name)
; Can also be the full path to a unix socket where mpd is running.
host = 127.0.0.1
port = 6600
password = 

; Seconds to sleep between progressbar/song timer sync
; Default: 1
interval = 2
;format-online = <icon-prev> <icon-seekb> <icon-stop> <toggle> <icon-seekf> <icon-next> <icon-repeat> <icon-random> <bar-progress> <label-time> <label-song>
format-online = <icon-prev> <icon-stop> <toggle> <icon-next>
format-playing-background = ${colors.background-alt}
format-playing-padding = 1
format-paused-background = ${colors.background-alt}
format-paused-padding = 1
format-stopped-background = ${colors.background-alt}
format-stopped-padding = 1
label-song = 󰽶 %artist:0:8:% - %title:0:10:..%
label-offline = 🎜 mpd is offline


icon-play = %{T3}%{F#6782ED}%{F-}%{T-}
icon-pause = %{T3}%{F#D29922}%{F-}%{T-}
icon-stop = %{T3}%{F#da4453}%{F-}%{T-}
icon-prev = 󰙣
icon-next = 󰙡  
icon-seekb = ⏮
icon-seekf = ⏭
icon-random = 
icon-repeat = 󰑖
icon-repeatone = 󰑘
icon-single = 🔂
icon-consume = ✀


toggle-on-foreground = #ff
toggle-off-foreground = #55

bar-progress-width = 16
bar-progress-indicator = %{F#D29922}󰮯 %{F-}
bar-progress-fill = ─
bar-progress-empty = 


[module/date]
type = internal/date
interval = 60
;date = %{F#d0d7de}%H:%M %p%{F-}
date = " %H:%M %p "
;date = %{T3} %H:%M -%{T1} %A %d.%m
date-alt = " %a/%d/%b, %H:%M %p "
label = %date%
format = <label>
format-background = ${colors.background-alt}
;format-padding = ${var.pad}
format-prefix = " 󰨲 " 
format-prefix-font = 3
format-prefix-foreground = ${colors.background}
format-prefix-background = ${colors.color14}

[module/lock]
type = internal/xkeyboard
;ignore :
format-margin = 0
blacklist-0 = num lock
blacklist-1 = scroll lock
format = <label-indicator>
label-indicator-padding = 0
indicator-icon-0 = caps lock;-CL;+CL
label-indicator-off =
label-indicator-on = "  CAPS "
format-foreground = ${colors.background}
format-background = ${colors.alert}

[module/memory]
type = internal/memory
interval = 15
label = %percentage_used:4:4%%
label-padding = ${var.pad}
format = <label>
format-prefix = ""
format-prefix-font = 3
format-prefix-foreground = ${colors.background}
format-prefix-background = ${colors.color9}
format-background = ${colors.background-alt}
format-prefix-padding = ${var.pad}

[module/cpu]
type = internal/cpu
interval = 3
label = %percentage:4:4%%
label-padding = ${var.pad}
format = <label>
format-prefix = ""
format-prefix-font = 3
format-prefix-foreground = ${colors.background}
format-prefix-background = ${colors.color9}
format-background = ${colors.background-alt} 
format-prefix-padding = ${var.pad}

[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
; Default: 100
full-at = 99

; format-low once this charge percentage is reached
; Default: 10
; New in version 3.6.0
low-at = 20

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = ADP0

; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 5
time-format = %H:%M

; Available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = <label-charging>
format-charging-foreground = ${colors.background}
format-charging-background = ${colors.background-alt}

format-charging-prefix = "󱘖"
format-charging-prefix-font = 3
format-charging-prefix-foreground = ${colors.background}
format-charging-prefix-background = ${colors.color9}
format-charging-prefix-padding = ${var.pad}

; Available tags:
;   <label-discharging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-discharging>
format-discharging =  <label-discharging>
format-discharging-foreground = ${colors.background}
format-discharging-background = ${colors.background-alt}

format-discharging-prefix = ""
format-discharging-prefix-font = 3
format-discharging-prefix-foreground = ${colors.background}
format-discharging-prefix-background = ${colors.color9}
format-discharging-prefix-padding = ${var.pad}

; Available tags:
;   <label-full> (default)
;   <bar-capacity>
;   <ramp-capacity>
format-full = <label-full>
format-full-foreground = ${colors.background}
format-full-background = ${colors.color9}

format-full-prefix = "󱊦"
format-full-prefix-font = 3
format-full-prefix-foreground = ${colors.background}
format-full-prefix-background = ${colors.color9}
format-full-prefix-padding = ${var.pad}


; Format used when battery level drops to low-at
; If not defined, format-discharging is used instead.
; Available tags:
;   <label-low>
;   <animation-low>
;   <bar-capacity>
;   <ramp-capacity>
; New in version 3.6.0
format-low = <animation-low> <label-low> 
format-low-foreground = ${colors.background}
format-low-background = ${colors.background-alt}

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current charge rate in watts)
label-charging =  %percentage:4:4%%
label-charging-foreground = ${colors.foreground}
label-charging-background = ${colors.background-alt}
label-charging-padding = ${var.pad} 

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = %percentage:4:4%% 
label-discharging-foreground = ${colors.foreground}
label-discharging-background = ${colors.background-alt}
label-discharging-padding = ${var.pad} 

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;label-full = Fully charged
label-full = %percentage:4:4%%
label-full-foreground = ${colors.foreground}
label-full-background = ${colors.background-alt}
label-full-padding = ${var.pad} 

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
; New in version 3.6.0
;label-low = BATTERY LOW
label-low = "󱊡"
label-low-foreground = ${colors.foreground}
label-low-background = ${colors.background-alt}
label-low-padding = ${var.pad} 

; Only applies if <ramp-capacity> is used
ramp-capacity-0 = "  "
ramp-capacity-1 = "  "
ramp-capacity-2 = "  "
ramp-capacity-3 = "  "
ramp-capacity-4 = "  "
ramp-capacity-foreground = ${colors.background}

; Only applies if <bar-capacity> is used
bar-capacity-width = 10

; Only applies if <animation-charging> is used
animation-charging-0 = " "
animation-charging-1 = " "
animation-charging-2 = " "
animation-charging-3 = " "
animation-charging-4 = " "
; Framerate in milliseconds
animation-charging-framerate = 750

; Only applies if <animation-discharging> is used
animation-discharging-0 = " "
animation-discharging-1 = " "
animation-discharging-2 = " "
animation-discharging-3 = " "
animation-discharging-4 = " "
; Framerate in milliseconds
animation-discharging-framerate = 500

; Only applies if <animation-low> is used
; New in version 3.6.0
animation-low-0 = !
animation-low-1 = 0
animation-low-framerate = 200


[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
label-connected-background = ${colors.background-alt}

format-disconnected = <label-disconnected>
label-disconnected-background = ${colors.background-alt}


[module/wlan]
inherit = network-base
interface-type = wireless

format-connected-suffix = ""
format-connected-suffix-foreground = ${colors.foreground}
format-connected-suffix-background = ${colors.background-alt}

# Urutan: Klik-Mulai | Warna-Simbol | Simbol | Reset-Warna | Nama-SSID | Klik-Selesai

label-connected = %{A1:~/.config/i3/polybar/scripts/network-manager.sh:}󰤨%essid%%{A}

label-connected-foreground = ${colors.background}
label-connected-background = ${colors.background-alt}
label-connected-padding = ${var.pad} 

format-disconnected-suffix = ""
format-disconnected-suffix-foreground = ${colors.foreground}
format-disconnected-background = ${colors.background-alt}

format-disconnected = <label-disconnected>

label-disconnected = %{A1:~/.config/i3/polybar/scripts/network-manager.sh:}󱛅%{A}
label-disconnected-foreground = ${colors.foreground}
label-disconnected-background = ${colors.background-alt}
label-disconnected-padding-left = ${var.pad} 


[module/eth]
inherit = network-base
interface-type = wired
speed-unit = 
ping-interval = 3
;label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%
;label-connected = %{F#F0C674}󰈀 %{F-}%ifname%
;label-connected = %{A1:~/.config/i3/polybar/script/network-manager.sh:}%{F#F0C674}󰈀 %{F-}%ifname%%{A}%{F-}%downspeed:9% %upspeed% %linkspeed%
# Simbol: 󰈀 (Eth), 󰇚 (Down), 󰇜 (Up), 󰱓 (Link)
;label-connected = %{A1:~/.config/i3/polybar/script/network-manager.sh:}%{F#d29922} 󰈀 %{F-}%downspeed%%{F#707880}󰶹%{F-}%{F#707880}󰶼%{F-}%upspeed% %{F#F0C674}󰱓 %{F-}%linkspeed%%{A}
;label-connected = %{A1:~/.config/i3/polybar/script/network-manager.sh:}%{F#d29922}󰈀 %{F-}%downspeed%%{F#707880}󰶹%{F-}%{F#707880}󰶼%{F-}%upspeed%%{A}
;label-connected = %{A1:~/.config/i3/polybar/script/network-manager.sh:}%{F#6782ED}󰈀 %{F-}%downspeed:2%%{A}

format-connected-prefix = "󰈀"
format-connected-prefix-font = 3
format-connected-prefix-foreground = ${colors.background}
format-connected-prefix-background = ${colors.color9}
format-connected-prefix-padding = ${var.pad}

label-connected = %{A1:~/.config/i3/polybar/scripts/network-manager.sh:} %downspeed:5:5%%{A}
label-connected-foreground = ${colors.foreground}
label-connected-background = ${colors.background-alt}
label-connected-padding-right = ${var.pad}

format-connected =  <label-connected>

label-disconnected = ""
label-disconnected-foreground = ${colors.background}
label-disconnected-background = ${colors.background-alt}
label-disconnected-padding = ${var.pad}
format-disconnected = <label-disconnected>

[module/pulseaudio]
type = internal/pulseaudio
; Use PA_VOLUME_UI_MAX (~153%) if true, or PA_VOLUME_NORM (100%) if false
; Default: true
master-soundcard = default
speaker-soundcard = default
headphone-soundcard = default

master-mixer = Master
use-ui-max = true
interval = 5
reverse-scroll = false
ramp-volume-0 = " "
ramp-volume-1 = " "
ramp-volume-2 = "󰕾 "
;ramp-volume-3 = " "

ramp-headphones-0 = " "
ramp-volume-0-foreground = ${colors.color1}
ramp-volume-1-foreground = ${colors.color2}
ramp-volume-2-foreground = ${colors.color3}
ramp-volume-3-foreground = ${colors.alert}
ramp-volume-0-background = ${colors.color9}
ramp-volume-1-background = ${colors.color9}
ramp-volume-2-background = ${colors.color9}
ramp-volume-3-background = ${colors.color9}
label-ramp-padding = ${var.pad}

label-volume = %percentage:2:3%%
format-volume = <label-volume>
label-volume-padding = ${var.pad}

format-volume-prefix = "󰕾"
format-volume-prefix-font = 3 
format-volume-prefix-foreground = ${colors.background}
format-volume-prefix-background = ${colors.color9}
format-volume-prefix-padding = ${var.pad}

format-volume-padding-right = ${var.pad}
format-volume-background = ${colors.background-alt}

label-muted-foreground = ${colors.alert}

format-muted = <label-muted>
label-muted-padding = ${var.pad}

format-muted-background = ${colors.background-alt}

format-muted-prefix = ""
format-muted-prefix-foreground = ${colors.alert}
format-muted-prefix-background = ${colors.color9}
format-muted-prefix-font = 3
format-muted-prefix-padding = ${var.pad}

click-right = pavucontrol

[module/i3]
type = internal/i3
pin-workspaces = false
show-urgent = true
strip-wsnumbers = true
index-sort = true
enable-click = true
enable-scroll = false
wrapping-scroll = false
reverse-scroll = false
fuzzy-match = true

; ws-icon-[0-9]+ = <label>;<icon>
; NOTE: The <label> needs to match the name of the i3 workspace
; Neither <label> nor <icon> can contain a semicolon (;)
ws-icon-0 = 1;♚
ws-icon-1 = 2;♛
ws-icon-2 = 3;♜
ws-icon-3 = 4;♝
ws-icon-4 = 5;♞
ws-icon-default = ♟
; NOTE: You cannot skip icons, e.g. to get a ws-icon-6
; you must also define a ws-icon-5.
; NOTE: Icon will be available as the %icon% token inside label-*

; Available tags:
;   <label-state> (default) - gets replaced with <label-(focused|unfocused|visible|urgent)>
;   <label-mode> (default)
format = <label-state> <label-mode>

; Available tokens:
;   %mode%
; Default: %mode%
label-mode = %mode%
label-mode-padding = 1
label-mode-background = #e60053

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-focused = %index%
label-focused-foreground = #ffffff
label-focused-background = #3f3f3f
label-focused-underline = #fba922
label-focused-padding = 2

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-unfocused = %index%
label-unfocused-foreground = #ffffff
label-unfocused-background = #3f3f3f
label-unfocused-padding = 2

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-visible = %index%
label-visible-foreground = #ffffff
label-visible-background = #3f3f3f
label-visible-underline = #555555
label-visible-padding = 2

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-urgent = %index%
label-urgent-foreground = #000000
label-urgent-background = #bd2c40
label-urgent-padding = 2

; Separator in between workspaces
label-separator = |
label-separator-padding = 2
label-separator-foreground = #ffb52a

[module/xworkspaces]
type = internal/xworkspaces
icon-0 = 1;󰖟
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-4 = 5;
icon-5 = 6;󰎄
icon-6 = 7;
icon-7 = 8;󰑋
icon-8 = 9;
icon-default = 


format = <label-state>
label-monitor = %name%
label-mode-padding = 1

format-prefix = ""
format-prefix-font = 6
format-prefix-foreground = #5c6970

format-suffix = ""
format-suffix-font = 6
format-suffix-foreground = #5c6970

label-active = %{B#5c6970}%{F#fff}%{T6}%{T-}%{B#fff}%{F#1A232E}%{T6} %icon% %{T-}%{F-}%{B#5c6970}%{F#fff}%{T6}%{T-}%{F-}%{B-} 

;label-active = %{F#555}%{T5}%{T-}%{B#555}%{F#555}   %icon%   %{F-}%{B-}%{F#555}%{T5}%{F-}%{T-}

;label-active = %icon% 
;label-active-foreground = ${colors.background}
label-active-background = ${colors.background-alt0}
label-active-padding = 0
;label-active-underline = #5c6970
;label-active-overline = #5c6970
label-active-font = 3

label-occupied = %icon%:%name%
label-occupied-foreground = ${colors.disabled}
label-occupied-background = #5c6970
label-occupied-padding = 1
label-occupied-font = 1

label-urgent = %icon%
label-urgent-foreground = #000000
label-urgent-background = #5c6970
label-urgent-underline = #9b0a20
label-urgent-padding = 1

label-empty = %icon%
label-empty-foreground = ${colors.background-alt0}
label-empty-background = #5c6970
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:28:28:..%
label-background = ${colors.background-alt}
label-padding = ${var.pad} 
label-empty = desktop

[module/backlight]
type = custom/script
exec = brightnessctl -m | cut -d, -f4
interval = 1

format-prefix = ""
format-prefix-foreground = ${colors.background}
format-background = ${colors.background-alt0}
format-prefix-padding-right = ${var.pad}
format-prefix-padding-left = ${var.pad}

label = %output%
label-background = ${colors.background-alt0}
label-padding-right = ${var.pad} 

; Scroll untuk ganti brightness
scroll-up = brightnessctl set +5%
scroll-down = brightnessctl set 5%-

[module/xbacklight]
type = internal/xbacklight
output = eDP
format = <ramp> <bar>

ramp-0 = 
ramp-0-foreground = #666
ramp-1 = 
ramp-1-foreground = #999
ramp-2 = 
ramp-2-foreground = #fff

bar-width = 12
bar-indicator = |
bar-indicator-font = 6
bar-indicator-foreground = #bbffffff
bar-fill = ─
bar-fill-font = 6
bar-fill-foreground = #9f78e1
bar-empty = ─
bar-empty-font = 6
bar-empty-foreground = #44

[module/light]
;type = internal/xbacklight
type = internal/backlight

; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
;card = intel_backlight
;card = amdgpu_bl0
;card = nv_backlight
card = amdgpu_bl1

enable-scroll = true
use-actual-brightness = true

; Available tags:
;   <label> (default)
;   <ramp>
;   <bar>
;format = <ramp><label>
format = <ramp>
format-background = ${colors.background-alt}
format-padding = 0

; Available tokens:
;   %percentage% (default)
;label = " %percentage%% "
;label-foreground = ${color.fg1}
;label-background = ${color.bg1}

; Only applies if <ramp> is used
ramp-0 = "󰃞"
ramp-1 = "󰃝"
ramp-2 = "󰃟"
ramp-3 = "󰃠"
ramp-4 = "󰃚"
ramp-foreground = ${colors.foreground}
ramp-background = ${colors.background-alt}
ramp-font = 3

[module/tray]
type = internal/tray
tray-spacing = 5 px
tray-background = ${colors.background-alt0}
format-padding = ${var.pad}
format-foreground = ${colors.background}
format-background = ${colors.background-alt0}

[module/sysmenu]
type = custom/text

format = 
format-font = 1
format-foreground = ${colors.foreground}
format-background = ${colors.alert}
format-padding = ${var.pad}

click-left = "i3-nagbar -f 'pango:monospace 11' -t warning -m ' Exit request detected  Do you really want to exit i3  This will end your X session.' -B 'Yes,  i3' 'i3-msg exit'"

;==========================================================
; MODULE UN-USED
;==========================================================

[module/filesystem]
type = internal/fs
interval = 60
mount-0 = /
label-mounted = %{F#F0C674}HDD%mountpoint%%{F-} %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

