

;==========================================================
; MODULE scripts
;==========================================================
[module/gammastep]
type = custom/script
# Only echo the icons here. Interval 2 is fine for checking if the process is alive.
exec = pgrep -x gammastep > /dev/null && echo " " || echo " 󱗤"
interval = 2
click-left = ~/.config/i3/polybar/scripts/gammastep-toggle.sh
label-foreground = ${colors.foreground}
label-background = ${colors.background-alt}

[module/weather]
type = custom/script
exec = ~/.config/i3/polybar/scripts/weather.sh
interval = 600
format-prefix = "󰖐 "
format-prefix-padding-left = 1
format-prefix-font = 1
format-prefix-foreground = ${colors.foreground}
format-prefix-background = ${colors.background-alt}

label = %output%
label-background = ${colors.background-alt}
label-min-width = 1
;label-padding = 1

; Klik kiri untuk melihat cuaca detail di terminal (alacritty/kitty/st)
click-left = st -e sh -c "curl wttr.in/batam; read"

[module/weather-full]
type = custom/script
exec = ~/.config/i3/polybar/scripts/weather-full.sh
interval = 6000

label = %output%
label-font = 1
label-background = ${colors.background-alt}
label-padding = 1

click-right = ~/.config/i3/polybar/scripts/weather-full.sh
click-left = kitty -e sh -c "curl wttr.in/batam; read"

[module/bluetooth]
type = custom/script
exec = ~/.config/i3/polybar/scripts/bluetooth.sh
interval = 5

; Warna saat aktif (Biru)
format-foreground = ${colors.foreground}
label = %output%
label-background = ${colors.background-alt}
label-padding = ${var.pad} 

; Klik kiri untuk buka manager (opsi)
;click-left = blueman-manager &
click-left = kitty bluetui &
; Klik kanan untuk toggle on/off
click-right = ~/.config/i3/polybar/scripts/bt_toggle.sh

[module/prayer]
type = custom/script
exec = ~/.config/i3/polybar/scripts/next_prayer.sh
format =  <label>
format-prefix = " 󰥹 "
format-foreground = ${colors.background}
format-background = ${colors.color6}
format-prefix-font = 3
;format-padding = ${var.pad}
label = %output%
label-foreground = ${colors.foreground}
label-background = ${colors.background-alt}
label-padding = ${var.pad} 


[module/fake-i3]
type = custom/script
exec = ~/.config/i3/polybar/scripts/fake-i3.sh
tail = false
interval = 0.2
label-background = ${colors.background-alt0}
;label-padding-left = ${var.pad}

; Agar bisa diklik untuk pindah workspace
;click-left = i3-msg workspace next_on_output
;click-right = i3-msg workspace prev_on_output

[module/caffein]
type = custom/script
exec = ~/.config/i3/polybar/scripts/caffein --status
interval = 3
click-left = ~/.config/i3/polybar/scripts/caffein --toggle
label = %output:0:30:...%
label-foreground = ${colors.foreground}
label-background = ${colors.background-alt}
label-padding = ${var.pad} 

[module/cava]
type = custom/script
tail = true
exec = $HOME/.config/i3/polybar/scripts/cava.sh
format = <label>
format-font = 5
label = %output%
label-foreground = #f9e2af

;==========================================================
; MODULE scripts UN-USED
;==========================================================
[module/network-manager]
type = custom/script
interval = 3
exec = "sh ~/.config/i3/polybar/scripts/network-manager.sh --status --enabled-color "#a6e3a1" --disabled-color "#f38ba8""
click-left = "sh ~/.config/i3/polybar/scripts/network-manager.sh"
label = "%output%"
format-background = ${colors.background-alt0}

[module/network-traffic]
type = custom/script
exec = ~/.config/i3/polybar/scripts/network-traffic.sh
tail = true

[module/info-hackspeed]
type = custom/script
exec = ~/.config/i3/polybar/scripts/info-hackspeed.sh
tail = true
;==========================================================
