#!/usr/bin/env bash

if [[ $COLS -gt 140 ]]; then
    rmpc remote --pid "$PID" set theme ~/.config/rmpc/themes/nord.ron
    rmpc remote --pid "$PID" status "Big theme set"
else 
    rmpc remote --pid "$PID" set theme ~/.config/rmpc/themes/catppuccin.ron
    rmpc remote --pid "$PID" status "Small theme set"
fi
