;
;	 ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ███████╗
;	██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔════╝
;	██║     ██║   ██║██║     ██║   ██║██████╔╝███████╗
;	██║     ██║   ██║██║     ██║   ██║██╔══██╗╚════██║
;	 ██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║███████║
; 	 ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

alpha = #0000ffff
bg = ${xrdb:background:#000000}
bg1 = #383d49
fg = ${xrdb:foreground:#ECEFF4}


;; for 50% transparent
trans1 = #80000000 
;; 100% transparent
trans2 = #00


;; colors
white = ${xrdb:color7:#ECEFF4}
black = ${xrdb:color0:#3B4252}
red = ${xrdb:color1:#EE383C}
lred = ${xrdb:color1:#d77c7e}
green = ${xrdb:color2:#A3BE8C}
yellow = ${xrdb:color3:#EBCB8B}
blue = ${xrdb:color4:#61afef}
ocean = #6381C4
bluedark = #3D59A1
indigo = #6C77BB
indigolight = #808bcf
cyan = ${xrdb:color6:#88c0d0}
purple = ${xrdb:color5:#be95ff}
lpurple = ${xrdb:color5:#CDB1FB}
teal = ${xrdb:color5:#599CAA}
orange = ${xrdb:color9:#FFA500}
lorange = ${xrdb:color9:#FFC251}
pink = #EF7CBB
magenta = #D84988

gray = #4D4D4D
lgray = #787878










;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
