; ____       _       _
;|  _ \ ___ | |_   _| |__   __ _ _ __
;| |_) / _ \| | | | | '_ \ / _` | '__|  z0mbi3
;|  __/ (_) | | |_| | |_) | (_| | |     https://github.com/gh0stzk/dotfiles
;|_|   \___/|_|\__, |_.__/ \__,_|_|     z0mbi3.zk@protonmail.com
;               |___/

[global/wm]

margin-bottom = 0
margin-top = 0

include-file = modules.ini

[color]
bg = #2d353b
fg = #d3c6aa

mbg = #f8f5e4
red = #e67e80
pink = #FF0677
purple = #d699b6
blue = #7fbbb3
blue-arch = #0A9CF5
cyan = #83c092
teal = #00B19F
green = #a7c080
lime = #B9C244
yellow = #dbbc7f
amber = #FBC02D
orange = #e69875
brown = #AC8476
grey = #272e33
indigo = #6C77BB
blue-gray = #2d353b

[bar/main]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = true

bottom = false
fixed-center = true

width = 98%
height = 2.8%

offset-x = 1%
offset-y = 5

background = ${color.bg}
foreground = ${color.fg}

radius = 15

line-size = 2
line-color = ${color.blue}

border-size = 3pt
border-color = ${color.bg}

padding = 1

module-margin-left = 0
module-margin-right = 0

; Text
font-0 = "JetBrainsMono Nerd Font Propo:style=Bold:size=12;3"
; Icons
font-1 = "Font Awesome 7 Free Solid:size=12;3"
font-2 = "Material Design Icons Desktop:size=11;3"
font-3 = "Material Design Icons Desktop:size=12;3"
;dpi = 96

;Modules availables but not active:
;	brightness xkeyboard
modules-left = launcher mpd_control sep xworkspaces 
modules-center =
modules-right =  sep usercard mplayer sep cpu_bar sep memory_bar sep filesystem sep battery sep wlan sep eth sep date sep pulseaudio sep power tray

separator =
dim-value = 1.0

;;locale = es_MX.UTF-8

wm-restack = i3
enable-ipc = true

cursor-click = pointer
cursor-scroll =

[settings]

screenchange-reload = true

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
