;
;	 ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ███████╗
;	██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔════╝
;	██║     ██║   ██║██║     ██║   ██║██████╔╝███████╗
;	██║     ██║   ██║██║     ██║   ██║██╔══██╗╚════██║
;	╚██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║███████║
;	 ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
;                                                 
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-

[color]

;bg = #0B0B0B
bg = #000
fg = #747474

;; for 100% transparent
trans100 = #00000000
;; 95%
trans95 = F2000000
;; for 85% transparent
trans85 = #D9000000
;; for 50% transparent
trans50 = #80000000

white1=#d8d5ce
white2=#dae3e0
white3=#cdc7b9
white4=#c9d0c8
white5=#afbab6
white6=#898a84

black = #16101C
white = #9a9a9a
red = #f7768e
green = #9ece6a
yellow = #e0af68
blue = #7aa2f7
purple = #bb9af7
cyan = #7dcfff
teal = #868DB1
brown = #272727
orange = #F45314
pink = #D545E7


bg1 = #1a1d23 
bg2 = #434c5e
bg3 = #3b4252
bg4 = #2b2f30


;; xrdb colors
;; Uncomment this if you want to use color from .Xdefaults or Xresources
;black = ${xrdb:color0}
;white = ${xrdb:color7}
;red = ${xrdb:color1}
;green = ${xrdb:color2}
;yellow = ${xrdb:color3}
;blue = ${xrdb:color4}
;purple = ${xrdb:color5}
;cyan = ${xrdb:color6}


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
