
[module/bib]
type = custom/text
label = "%{T3}%{T-}"
label-foreground = ${color.bg-alt}
label-background = ${color.bg}

[module/biy]
type = custom/text
label = "%{T3}%{T-}"
label-foreground = ${color.grey}
label-background = ${color.bg-alt}

[module/bir]
type = custom/text
label = "%{T3}%{T-}"
label-foreground = ${color.bg-alt}
label-background = ${color.grey}

[module/bdgg2]
type = custom/text
label = "%{T3}%{T-}"
label-foreground = ${color.bg-alt}
label-background = ${color.bg}

######################################################

[module/bdv]
type = custom/text
label = "%{T3}%{T-}"
label-foreground = ${color.bg-alt}
label-background = ${color.bg}

[module/bdv2]
type = custom/text
label = "%{T3}%{T-}"
label-foreground = ${color.bg-alt}
label-background = ${color.bg}

[module/bdv3]
type = custom/text
label = "%{T3}%{T-}"
label-foreground = ${color.grey}
label-background = ${color.bg}

[module/bdy]
type = custom/text
label = "%{T3}%{T-}"
label-foreground = ${color.grey}
label-background = ${color.bg}

[module/bdr]
type = custom/text
label = "%{T3}%{T-}"
label-foreground = ${color.grey}
label-background = ${color.bg-alt}

[module/bdp]
type = custom/text
label = "%{T3}%{T-}"
label-foreground = ${color.grey}
label-background = ${color.bg-alt}

[module/bdc]
type = custom/text
label = "%{T3}%{T-}"
label-foreground = ${color.bg-alt}
label-background = ${color.grey}
