[files]
current_page=-1
recent_files=/home/lenoarch/.config/net.imput.helium/Local State;/home/lenoarch/.config/net.imput.helium/Default/Preferences;/home/lenoarch/.config/mouse-actions.json;/home/lenoarch/.config/pacseek/config.json;/home/lenoarch/.config/gtk-2.0/gtkfilechooser.ini;/home/lenoarch/.config/i3/polybar/themes/cyber/modules.ini;/home/lenoarch/.local/bin/organize-downloads.sh;/home/lenoarch/.config/i3/polybar/themes/cyber/addons.sh;/home/lenoarch/.config/i3/polybar/themes/cyber/dunstrc;/home/lenoarch/.config/i3/polybar/themes/catppuccin/addons.sh;
recent_projects=

[project]
session_file=
project_file_path=/home/lenoarch/Projects

[geany]
treeview_position=1554
msgwindow_position=997
geometry=0;36;1914;1038;1;
sidebar_page=3

[search]
find_all_expanded=true
replace_all_expanded=true
position_find_x=633
position_find_y=408
position_replace_x=626
position_replace_y=390
position_fif_x=607
position_fif_y=388

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=/usr/lib/geany/addons.so;/usr/lib/geany/markdown.so;/usr/lib/geany/overview.so;/usr/lib/geany/treebrowser.so;

[VTE]
last_dir=/home/lenoarch
