[files]
current_page=0
FILE_NAME_0=5198;Conf;0;EUTF-8;1;1;1;%2Fhome%2Flenoarch%2F.config%2Fi3%2Frules.conf;0;4
FILE_NAME_1=164;Sh;0;EUTF-8;1;1;1;%2Fhome%2Flenoarch%2F.local%2Fbin%2Fyad-power-profile;0;4
FILE_NAME_2=0;None;0;EUTF-8;1;1;1;%2Fhome%2Flenoarch%2F.config%2Fi3%2F.current_theme;0;4
FILE_NAME_3=4016;Conf;0;EUTF-8;1;1;1;%2Fhome%2Flenoarch%2F.config%2Fi3%2Fpolybar%2Fthemes%2Fnightfox%2Fmodules.ini;0;4
FILE_NAME_4=1784;Conf;0;EUTF-8;1;1;1;%2Fhome%2Flenoarch%2F.config%2Fi3%2Fpolybar%2Fthemes%2Fnightfox%2Fconfig.ini;0;4
FILE_NAME_5=335;Conf;0;EUTF-8;1;1;1;%2Fhome%2Flenoarch%2F.config%2Fi3%2Fpolybar%2Fthemes%2Fnightfox%2Fscript-module.ini;0;4
FILE_NAME_6=10135;Conf;0;EUTF-8;1;1;1;%2Fhome%2Flenoarch%2F.config%2Fi3%2Fsxhkd%2Fsxhkdrc;0;4
FILE_NAME_7=218;Sh;0;EUTF-8;1;1;1;%2Fhome%2Flenoarch%2F.config%2Fi3%2Fscripts%2Fvolume-dunst.sh;0;4
FILE_NAME_8=168;Markdown;0;EUTF-8;1;1;1;%2Fhome%2Flenoarch%2F.config%2Fi3%2Fpolybar%2Fthemes%2Fdecor.md;0;4

[VTE]
last_dir=/home/lenoarch/.local/bin
