[colors]
background = #161616
background-alt = #373B41
foreground = #C5C8C6
primary = #33b1ff
secondary = #be95ff
alert = #A54242
disabled = #7b7c7e
border = #161616

trans50 = #80000000

white = #e4e4e5
black = #484848
red = #f16da6
lime = #99bf82
blue = #8cb6ff
yellow = #C7A92D
orange = #FFA15F
cyan = #08bdba
magenta = #D84988
silver = #c0c0c0
gray = #808080
maroon = #800000
olive = #B5B536
green = #119966
purple = #be95ff
teal = #52bdff
navy = #005475

blue2 = #859ee0
blue3 = #303347
blue4 = #232535
red2 = #d77c7e

pink = #b892d0

;scheme: "carbonfox"
;author: "EdenEast"

;base00: "#161616"
;base01: "#252525"
;base02: "#353535"
;base03: "#484848"
;base04: "#7b7c7e"
;base05: "#f2f4f8"
;base06: "#b6b8bb"
;base07: "#e4e4e5"
;base08: "#ee5396"
;base09: "#3ddbd9"
;base0A: "#08bdba"
;base0B: "#25be6a"
;base0C: "#33b1ff"
;base0D: "#78a9ff"
;base0E: "#be95ff"
;base0F: "#ff7eb6"
