[module/sep]
type = custom/text
format = " "
format-font = 2
format-background = ${colors.background}
format-foreground = ${colors.background}
;format-padding = 1

[module/sep1]
type = custom/text
format = 
format-font = 2
format-background = ${colors.cyan}
format-foreground = ${colors.purple}
format-padding-left = 2

[module/sep2]
type = custom/text
format = 
format-font = 2
format-background = ${colors.lime}
format-foreground = ${colors.green}
format-padding-left = 2

[module/sep3]
type = custom/text
format = 
format-font = 2
format-background = ${colors.blue}
format-foreground = ${colors.lime}
format-padding-left = 2

[module/sep4]
type = custom/text
format = 
format-font = 2
format-background = ${colors.yellow}
format-foreground = ${colors.blue}
format-padding-left = 2

[module/sep5]
type = custom/text
format = 
format-font = 2
format-background = ${colors.magenta}
format-foreground = ${colors.yellow}
format-padding-left = 2

[module/sep6]
type = custom/text
format = 
format-font = 2
format-background = ${colors.teal}
format-foreground = ${colors.magenta}
format-padding-left = 2

[module/sep7]
type = custom/text
format = 
format-font = 2
format-background = ${colors.navy}
format-foreground = ${colors.teal}
format-padding-left = 2

[module/gtg]
type = custom/text
format = 
format-font = 2
format-background = ${colors.green}
format-foreground = ${colors.cyan}
format-padding-left = 2


[module/sepl]
type = custom/text
format = 
format-font = 2
format-background = ${colors.background-alt}
format-foreground = ${colors.background}
;format-padding = 1

[module/l1]
type = custom/text
format = 
format-font = 2
format-foreground = ${colors.background-alt}

[module/l2]
type = custom/text
format = 
format-font = 2
format-foreground = ${colors.background-alt0}
format-background = ${colors.background-alt}

[module/r1]
type = custom/text
format = 
format-font = 2
format-foreground = ${colors.background-alt}

[module/r2]
type = custom/text
format = 
format-font = 2
format-foreground = ${colors.background-alt0}
format-background = ${colors.background-alt}

[module/c1]
type = custom/text
format = 
format-font = 2
format-foreground = ${colors.background-alt}

[module/c2]
type = custom/text
format = 
format-font = 2
format-foreground = ${colors.background-alt}

[module/c3]
type = custom/text
format = 
format-font = 7
format-foreground = ${colors.background-alt}
;format-background = ${colors.background}

[module/c4]
type = custom/text
format = 
format-font = 7
format-foreground = ${colors.background-alt0}
;format-background = ${colors.background-alt0}


[module/t1]
type = custom/text
format = 
format-font = 2
format-foreground = ${colors.background-alt0}
format-background = ${colors.background}

[module/t2]
type = custom/text
format = 
format-font = 2
format-foreground = ${colors.background-alt}


[module/t4]
type = custom/text
format = 
format-font = 2
format-foreground = ${colors.background-alt0}
format-background = ${colors.background}

[module/a1]
type = custom/text
format = 
format-font = 2
format-foreground = ${colors.background-alt}
format-background = ${colors.background}-alt}


[module/a2]
type = custom/text
format = 
format-font = 2
format-foreground = ${colors.background-alt0}
format-background = ${colors.background}

[module/b1]
type = custom/text
format = 
format-font = 2
format-foreground = ${colors.background-alt}
format-background = ${colors.background}

[module/b2]
type = custom/text
format = 
format-font = 2
format-foreground = ${colors.background-alt}
format-background = ${colors.background}

