; This module is not active by default (to enable it, add it to one of the
; modules-* list above).
; Please note that only a single tray can exist at any time. If you launch
; multiple bars with this module, only a single one will show it, the others
; will produce a warning. Which bar gets the module is timing dependent and can
; be quite random.
; For more information, see the documentation page for this module:
; https://polybar.readthedocs.io/en/stable/user/modules/tray.html

[module/systray]
type = internal/tray

format-margin = 0pt
tray-padding = 5pt
tray-spacing = 16pt
tray-foreground = ${colors.background}
tray-background = ${colors.purple}
format-foreground = ${colors.purple}
format-background = ${colors.purple}

[module/xworkspaces]
type = internal/xworkspaces

label-active = " %name% "
label-active-foreground = ${colors.foreground}
label-active-background = ${colors.navy}
label-active-underline= ${colors.trans50}
label-active-padding = 0

label-occupied = "▫%name% "
label-occupied-padding = 0
label-occupied-foreground = ${colors.foreground}
label-occupied-background = ${colors.black}

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = "%{B#1A1A1A}%{F#BFBFBF}  %{F-}%{B-} %title:0:15:...%"

label-empty = "%{B#1A1A1A}%{F#BFBFBF} 󰣇 %{F-}%{B-} desktop"

[module/filesystem]
type = internal/fs
interval = 300

mount-0 = /

label-mounted = "%percentage_used%% "
label-mounted-foreground = ${colors.background}
label-mounted-background = ${colors.teal}

format-mounted-prefix = " 󰔚 "
format-mounted-background = ${colors.teal}
format-mounted-foreground = ${colors.background}

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}
label-unmounted-background = ${colors.teal}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "  "
format-prefix-foreground = ${colors.background}
format-prefix-background = ${colors.magenta}
label = "%percentage_used:2%% "
label-background = ${colors.magenta}
label-foreground = ${colors.background}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "  "
format-prefix-foreground = ${colors.background}
format-prefix-background = ${colors.yellow}
label ="%percentage:2%% "
label-background = ${colors.yellow}
label-foreground = ${colors.background}

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = "%netspeed:5:5% "
label-connected-foreground = ${colors.background}
label-connected-background = ${colors.blue}

label-disconnected = " 󱚼 null "
label-disconnected-foreground = ${colors.background}
label-disconnected-background = ${colors.blue}

[module/eth]
inherit = network-base
interface-type = wired
label-connected = "%netspeed:5:5:% "
label-connected-foreground = ${colors.background}
label-connected-background = ${colors.lime}

format-connected-prefix = "  "
format-connected-prefix-foreground = ${colors.background}
format-connected-prefix-background = ${colors.lime}

label-disconnected = " 󰈀 disconnected "
label-disconnected-foreground = ${colors.background}
label-disconnected-background = ${colors.lime}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = " 󰕾 "
format-volume-prefix-foreground = ${colors.background}
format-volume-prefix-background = ${colors.purple}

format-volume = <label-volume>

label-volume = "%percentage:3:3%% "
label-volume-foreground = ${colors.background}
label-volume-background = ${colors.purple}

label-muted = " MUTED "
label-muted-foreground = ${colors.disabled}
label-muted-background = ${colors.purple}

[module/date]
type = internal/date
interval = 1

date = "%H:%M "
date-alt = %Y-%m-%d %H:%M:%S

label =  %date%
format = <label>
format-prefix = " 󱦟 "
format-background = ${colors.cyan}
format-foreground = ${colors.background}

label-foreground = ${colors.background}
label-background = ${colors.cyan}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.background}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
full-at = 99

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = ACAD

; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 2

; see "man date" for details on how to format the time string
; NOTE: if you want to use syntax tags here you need to use %%{...}
; Default: %H:%M:%S
time-format = %H:%M

; Available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = <animation-charging><label-charging>
format-charging-prefix = ""
format-charging-prefix-font = 1
format-charging-prefix-foreground = ${colors.background}
format-charging-background = ${colors.green}

; Available tags:
;   <label-discharging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-discharging>
;format-discharging-prefix = ""
format-discharging = <label-discharging>
format-discharging-prefix = " "
format-discharging-prefix-font = 1
format-discharging-prefix-foreground = ${colors.background}
format-discharging-prefix-background = ${colors.bg1}
format-discharging-background = ${colors.green}


; Available tags:
;   <label-full> (default)
;   <bar-capacity>
;   <ramp-capacity>
format-full = <label-full>
format-full-prefix = " "
format-full-prefix-font = 1
format-full-prefix-foreground = ${colors.background}
format-full-background = ${colors.green}

; Available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current charge rate in watts)
label-charging =  " %percentage%% "
label-charging-foreground = ${colors.background}
label-charging-background = ${colors.green}

; Available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = " %percentage%% "
label-discharging-foreground = ${colors.background}
label-discharging-background = ${colors.green}

; Available tokens:
;   %percentage% (default)
label-full = " %percentage%% "
label-full-foreground = ${colors.background}
label-full-background = ${colors.green}

; Only applies if <ramp-capacity> is used
ramp-capacity-0 = "  "
ramp-capacity-1 = "  "
ramp-capacity-2 = "  "
ramp-capacity-3 = "  "
ramp-capacity-4 = "  "
ramp-capacity-foreground = ${colors.background}
ramp-capacity-background = ${colors.green}
ramp-capacity-font = 1

; Only applies if <bar-capacity> is used
;bar-capacity-width = 10

; Only applies if <animation-charging> is used
animation-charging-0 = " "
animation-charging-1 = " "
animation-charging-2 = " "
animation-charging-3 = " "
animation-charging-4 = " "
animation-charging-foreground = ${colors.background}
animation-charging-background = ${colors.green}
animation-charging-font = 1

; Framerate in milliseconds
animation-charging-framerate = 700

; Only applies if <animation-discharging> is used
;;animation-discharging-0 = ${battery.anim0}
;;animation-discharging-1 = ${battery.anim1}

; Framerate in milliseconds
;animation-discharging-framerate = 500
