;
;	 ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ███████╗
;	██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔════╝
;	██║     ██║   ██║██║     ██║   ██║██████╔╝███████╗
;	██║     ██║   ██║██║     ██║   ██║██╔══██╗╚════██║
;	 ██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║███████║
; 	 ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

alpha = #0000ffff
bg = #2E3440
bg1 = #434C5E
fg = #ECEFF4
fg1 = #D8DEE9
fg2 = #9097a0
fg3 = #CBCDD1


;; for 50% transparent
trans1 = #80000000 
;; 100% transparent
trans2 = #00

;; dark
nord1 = #2e3440
nord2 = #3b4252
nord3 = #434c5e
nord4 = #4c566a

;; light
nord5 = #d8dee9
nord6 = #e5e9f0
nord7 = #eceff4

;; colors
black = #3B4252
red = #BF616A
green = #A3BE8C
yellow = #EBCB8B
blue = #81A1C1
purple = #B48EAD
cyan = #88c0d0
teal = #8FBCBB
white = #ECEFF4
indigo = #5E81AC
orange = #D08770
pink =


;; xrdb colors
;; Uncomment this if you want to use color from .Xdefaults or Xresources
;black = ${xrdb:color0}
;white = ${xrdb:color7}
;red = ${xrdb:color1}
;green = ${xrdb:color2}
;yellow = ${xrdb:color3}
;blue = ${xrdb:color4}
;purple = ${xrdb:color5}
;cyan = ${xrdb:color6}

;pallete

;#define nord0 #2E3440
;#define nord1 #3B4252
;#define nord2 #434C5E
;#define nord3 #4C566A
;#define nord4 #D8DEE9
;#define nord5 #E5E9F0
;#define nord6 #ECEFF4
;#define nord7 #8FBCBB
;#define nord8 #88C0D0
;#define nord9 #81A1C1
;#define nord10 #5E81AC
;#define nord11 #BF616A
;#define nord12 #D08770
;#define nord13 #EBCB8B
;#define nord14 #A3BE8C
;#define nord15 #B48EAD

;*.foreground:   nord4
;*.background:   nord0
;*.cursorColor:  nord4
;*fading: 35
;*fadeColor: nord3
;
;*.color0: nord1
;*.color1: nord11
;*.color2: nord14
;*.color3: nord13
;*.color4: nord9
;*.color5: nord15
;*.color6: nord8
;*.color7: nord5
;*.color8: nord3
;*.color9: nord11
;*.color10: nord14
;*.color11: nord13
;*.color12: nord9
;*.color13: nord15
;*.color14: nord7
;*.color15: nord6
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
