[module/sep]
type = custom/text
format = " "
format-font = 8
format-background = ${colors.background}
format-foreground = ${colors.background}
;format-padding = 1

[module/sep1]
type = custom/text
format = 
format-font = 5
format-background = ${colors.background-alt}
format-foreground = ${colors.background-alt0}
;format-padding = 1

[module/sepl]
type = custom/text
format = 
format-font = 5
format-background = ${colors.background-alt}
format-foreground = ${colors.background}
;format-padding = 1

[module/l1]
type = custom/text
format = 
format-font = 5
format-foreground = ${colors.background-alt}

[module/l2]
type = custom/text
format = 
format-font = 5
format-foreground = ${colors.background-alt0}
format-background = ${colors.background-alt}

[module/r1]
type = custom/text
format = 
format-font = 5
format-foreground = ${colors.background-alt}

[module/r2]
type = custom/text
format = 
format-font = 5
format-foreground = ${colors.background-alt0}
format-background = ${colors.background-alt}

[module/c1]
type = custom/text
format = 
format-font = 6
format-foreground = ${colors.background-alt}

[module/c2]
type = custom/text
format = 
format-font = 6
format-foreground = ${colors.background-alt}

[module/c3]
type = custom/text
format = 
format-font = 7
format-foreground = ${colors.background-alt}
;format-background = ${colors.background}

[module/c4]
type = custom/text
format = 
format-font = 7
format-foreground = ${colors.background-alt0}
;format-background = ${colors.background-alt0}


[module/t1]
type = custom/text
format = 
format-font = 6
format-foreground = ${colors.background-alt0}
format-background = ${colors.background}

[module/t2]
type = custom/text
format = 
format-font = 5
format-foreground = ${colors.background-alt}


[module/t4]
type = custom/text
format = 
format-font = 6
format-foreground = ${colors.background-alt0}
format-background = ${colors.background}

[module/a1]
type = custom/text
format = 
format-font = 6
format-foreground = ${colors.background-alt}
format-background = ${colors.background}-alt}


[module/a2]
type = custom/text
format = 
format-font = 6
format-foreground = ${colors.background-alt0}
format-background = ${colors.background}

[module/b1]
type = custom/text
format = 
format-font = 6
format-foreground = ${colors.background-alt}
format-background = ${colors.background}

[module/b2]
type = custom/text
format = 
format-font = 6
format-foreground = ${colors.background-alt}
format-background = ${colors.background}

