
[module/bgi]
type                      = custom/text
label                     = "%{T4}%{T-}"
label-foreground          = ${color.green}
label-background          = ${color.bg}

[module/bri]
type                      = custom/text
label                     = "%{T4}%{T-}"
label-foreground          = ${color.red}
label-background          = ${color.bg}

[module/byi]
type                      = custom/text
label                     = "%{T4}%{T-}"
label-foreground          = ${color.yellow}
label-background          = ${color.bg}

[module/bpi]
type                      = custom/text
label                     = "%{T4}%{T-}"
label-foreground          = ${color.purple}
label-background          = ${color.bg}

[module/bbi]
type                      = custom/text
label                     = "%{T4}%{T-}"
label-foreground          = ${color.blue}
label-background          = ${color.bg}

[module/boi]
type                      = custom/text
label                     = "%{T4}%{T-}"
label-foreground          = ${color.orange}
label-background          = ${color.bg}

[module/bii]
type                      = custom/text
label                     = "%{T4}%{T-}"
label-foreground          = ${color.indigo}
label-background          = ${color.bg}

[module/bgd]
type                      = custom/text
label                     = "%{T4}%{T-}"
label-foreground          = ${color.bg}
label-background          = ${color.green}

[module/brd]
type                      = custom/text
label                     = "%{T4}%{T-}"
label-foreground          = ${color.bg}
label-background          = ${color.red}

[module/byd]
type                      = custom/text
label                     = "%{T4}%{T-}"
label-foreground          = ${color.bg}
label-background          = ${color.yellow}

[module/bpd]
type                      = custom/text
label                     = "%{T4}%{T-}"
label-foreground          = ${color.bg}
label-background          = ${color.purple}

[module/bbd]
type                      = custom/text
label                     = "%{T4}%{T-}"
label-foreground          = ${color.bg}
label-background          = ${color.blue}

[module/bod]
type                      = custom/text
label                     = "%{T4}%{T-}"
label-foreground          = ${color.bg}
label-background          = ${color.orange}

[module/bid]
type                      = custom/text
label                     = "%{T4}%{T-}"
label-foreground          = ${color.bg}
label-background          = ${color.indigo}

[module/batr]
type                      = custom/text
label                     = "%{T4}%{T-}"
label-foreground          = ${color.lime}
label-background          = ${color.bg}

[module/batl]
type                      = custom/text
label                     = "%{T4}%{T-}"
label-foreground          = ${color.bg}
label-background          = ${color.lime}

######################################################

[module/sep1]
type = custom/text
format = 
format-font = 5
format-background = ${colors.background-alt}
format-foreground = ${colors.background-alt0}
;format-padding = 1

[module/sepl]
type = custom/text
format = 
format-font = 5
format-background = ${colors.background-alt}
format-foreground = ${colors.background}
;format-padding = 1

[module/l1]
type = custom/text
format = 
format-font = 5
format-foreground = ${colors.background-alt}

[module/l2]
type = custom/text
format = 
format-font = 5
format-foreground = ${colors.background-alt0}
format-background = ${colors.background-alt}

[module/r1]
type = custom/text
format = 
format-font = 5
format-foreground = ${colors.background-alt}

[module/r2]
type = custom/text
format = 
format-font = 5
format-foreground = ${colors.background-alt0}
format-background = ${colors.background-alt}

[module/c1]
type = custom/text
format = 
format-font = 6
format-foreground = ${colors.background-alt}

[module/c2]
type = custom/text
format = 
format-font = 6
format-foreground = ${colors.background-alt}

[module/c3]
type = custom/text
format = 
format-font = 7
format-foreground = ${colors.background-alt}
;format-background = ${colors.background}

[module/c4]
type = custom/text
format = 
format-font = 7
format-foreground = ${colors.background-alt0}
;format-background = ${colors.background-alt0}


[module/t1]
type = custom/text
format = 
format-font = 6
format-foreground = ${colors.background-alt0}
format-background = ${colors.background}

[module/t2]
type = custom/text
format = 
format-font = 5
format-foreground = ${colors.background-alt}


[module/t4]
type = custom/text
format = 
format-font = 6
format-foreground = ${colors.background-alt0}
format-background = ${colors.background}

[module/a1]
type = custom/text
format = 
format-font = 6
format-foreground = ${colors.background-alt}
format-background = ${colors.background}-alt}


[module/a2]
type = custom/text
format = 
format-font = 6
format-foreground = ${colors.background-alt0}
format-background = ${colors.background}

[module/b1]
type = custom/text
format = 
format-font = 6
format-foreground = ${colors.background-alt}
format-background = ${colors.background}

[module/b2]
type = custom/text
format = 
format-font = 6
format-foreground = ${colors.background-alt}
format-background = ${colors.background}

